---
title: "BIO624_Sbenedicti_PCA"
author: "Manav Rohilla, Dylan Hermosillo"
date: "2026-03-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r pca, echo=FALSE}
library(tidyverse) #Needed to combine the PLINK clustering out file/table with the sample information CSV (this is needed for plotting the PCA with coasts color-coded)

setwd("MODIFY AS NEEDED")

#Below: read in the PCA and the sample information sheet
eigenvec <- read.table("STEP4_FILESET.eigenvec")

sample_info <- read.csv("sample_name_mapping_final.csv",header=TRUE)

#Below: only need sample IDs and information regarding coast, sex, or developmental type
sample_info_coast <- sample_info %>% select("SampleID","Coast")
sample_info_sex <- sample_info %>% select("SampleID","Sex")
sample_info_dev <- sample_info %>% select("SampleID","Dev_Type")
sample_info_loc <- sample_info %>% select("SampleID","Location")

#Below: merging sample_info_coast/sex/dev with the eigenvec file requires actual column names for the eigenvec dataframe (not generated by PLINK)
colnames(eigenvec) <- c("Family","SampleID","PC1","PC2","PC3","PC4","PC5","PC6","PC7","PC8","PC9","PC10","PC11","PC12","PC13","PC14","PC15","PC16","PC17","PC18","PC19","PC20")

#Below: must rename sample IDs in the sample_info sheet to match the ones in the eigenvec file for proper merging
sample_info_coast$SampleID <- sapply(strsplit(sample_info_coast$SampleID, "\\."), "[",1)
sample_info_coast$SampleID <- sapply(strsplit(sample_info_coast$SampleID, "_"), function(string) paste(string[1:3], collapse = "_"))

sample_info_sex$SampleID <- sapply(strsplit(sample_info_sex$SampleID, "\\."), "[",1)
sample_info_sex$SampleID <- sapply(strsplit(sample_info_sex$SampleID, "_"), function(string) paste(string[1:3], collapse = "_"))

sample_info_dev$SampleID <- sapply(strsplit(sample_info_dev$SampleID, "\\."), "[",1)
sample_info_dev$SampleID <- sapply(strsplit(sample_info_dev$SampleID, "_"), function(string) paste(string[1:3], collapse = "_"))

sample_info_loc$SampleID <- sapply(strsplit(sample_info_loc$SampleID, "\\."), "[",1)
sample_info_loc$SampleID <- sapply(strsplit(sample_info_loc$SampleID, "_"), function(string) paste(string[1:3], collapse = "_"))

#Merge eigenvec and sample_info_coast/sex/dev. Since both files contain "sampleID" column, that column will be used as the basis for merging (this is required for color-coding the datapoints)
eigenvec_new_coast <- left_join(eigenvec,sample_info_coast)
eigenvec_new_sex <- left_join(eigenvec,sample_info_sex)
eigenvec_new_dev <- left_join(eigenvec,sample_info_dev)
eigenvec_new_loc <- left_join(eigenvec,sample_info_loc)

#Get percentage of variance

#Method identified from the following:
#https://medium.com/data-science/a-one-stop-shop-for-principal-component-analysis-5582fb7e0a9c

#https://www.jcmedu.org/jcmedu-articles/data-reduction-using-principal-component-analysis-theoretical-underpinnings-and-practical-applications-in-public-health-105124.html#:~:text=After%20obtaining%20the%20PCs%2C%20to%20calculate%20the,the%20variance%20of%20the%20data%20set%2C%20respectively.

eigenvals <- read.table("STEP4_FILESET.eigenval")
eigenvals_total <- sum(eigenvals$V1)
proportions <- lapply(eigenvals$V1,function(x) x / eigenvals_total)
percent_var_PC1 <- proportions[[1]]*100
percent_var_PC2 <- proportions[[2]]*100
#print(percent_var_PC1)
#print(percent_var_PC2)

#Below: generat PCA plot and color code by coast
ggplot(eigenvec_new_coast, aes(x = PC1, y = PC2, color = Coast)) + labs(title = "PCA Plot",subtitle = "Color-Coded by Coast", x = paste("PC1 Percentage of Variance:",percent_var_PC1,"%"), y = paste("PC2 Percentage of Variance:", percent_var_PC2,"%")) + geom_point(size = 2, alpha=0.5)

#Below: other PCA plots
ggplot(eigenvec_new_sex, aes(x = PC1, y = PC2, color = Sex)) + labs(title = "PCA Plot",subtitle = "Color-Coded by Sex", x = paste("PC1 Percentage of Variance:",percent_var_PC1,"%"), y = paste("PC2 Percentage of Variance:",percent_var_PC2,"%")) + geom_point(size = 2, alpha=0.5)

ggplot(eigenvec_new_dev, aes(x = PC1, y = PC2, color = Dev_Type)) + labs(title = "PCA Plot",subtitle = "Color-Coded by Developmental Type",  x = paste("PC1 Percentage of Variance:",percent_var_PC1,"%"), y = paste("PC2 Percentage of Variance:",percent_var_PC2,"%")) + geom_point(size = 2, alpha=0.5)

ggplot(eigenvec_new_loc, aes(x = PC1, y = PC2, color = Location)) + labs(title = "PCA Plot",subtitle = "Color-Coded by Location",  x = paste("PC1 Percentage of Variance:",percent_var_PC1,"%"), y = paste("PC2 Percentage of Variance:",percent_var_PC2,"%")) + geom_point(size = 2, alpha=0.5)
```